version: "3.7"

x-default-variables: &default-variables
  LOG_LEVEL: ${LOG_LEVEL-INFO}
  LOG_FORMAT: ${LOG_FORMAT-json}
  MANIFEST_PATH: ${MANIFEST_PATH-/manifests}
  TEST_DATA: ${TEST_DATA-}
  HTTP_PORT: ${HTTP_PORT-8080}
  HTTP_HOST: ${HTTP_HOST-0.0.0.0}
  HEALTH_PORT: ${HEALTH_PORT-8081}
  DB_TLS_SSLMODE: ${DB_TLS_SSLMODE-disable}
  DB_TLS_CERT: ${DB_TLS_CERT-}
  DB_TLS_KEY: ${DB_TLS_KEY-}
  DB_TLS_CA: ${DB_TLS_CA-}
  DB_HOST: ${DB_HOST-}
  DB_PORT: ${DB_PORT-}
  DB_DATABASE: ${DB_DATABASE-}
  DB_POOLSIZE: ${DB_POOLSIZE-}
  DB_POOL_TIMEOUT: ${DB_POOL_TIMEOUT-}

x-container-common: &container-common
  image: golang:1.16-buster
  entrypoint: /bin/main

x-qkm-common: &qkm-common
  DB_HOST: postgres

services:
  migration:
    <<: *container-common
    environment:
      <<: *default-variables
      <<: *qkm-common
    networks:
      - qkm
    command: migrate up
    restart: "on-failure"
    volumes:
      - ./build/bin/key-manager:/bin/main:ro
      - ./deps/migrations:/migrations:ro
      - ./deps/config/certificates:/certificates
      - ./deps/config/ca:/ca:ro

  key-manager:
    <<: *container-common
    environment:
      <<: *default-variables
      <<: *qkm-common
      AUTH_OIDC_CA_CERT: ${AUTH_OIDC_CA_CERT-}
      AUTH_OIDC_ISSUER_URL: ${AUTH_OIDC_ISSUER_URL-}
      HTTPS_ENABLED: ${HTTPS_ENABLED-}
      HTTPS_SERVER_KEY: ${HTTPS_SERVER_KEY-}
      HTTPS_SERVER_CERT: ${HTTPS_SERVER_CERT-}
      AUTH_TLS_CA: ${AUTH_TLS_CA-}
      AUTH_API_KEY_FILE: ${AUTH_API_KEY_FILE-}
      GODEBUG: x509ignoreCN=0 # Temporary ENV var while we generate new certs that are compliant with the new golang behavior: https://geekflare.com/san-ssl-certificate/
    ports:
      - 8080:8080
      - 8081:8081
      - 8443:8443
    depends_on:
      - migration
    networks:
      - quorum
      - besu
      - hashicorp
      - qkm
    command: run
    restart: "on-failure"
    volumes:
      - ./build/bin/key-manager:/bin/main:ro
      - ./deps/config/manifests:/manifests:ro
      - ./deps/config/certificates:/certificates:ro
      - ./deps/config/ca:/ca:ro
      - ./deps/config/apikey:/apikey:ro
      - hashicorp-token:/vault/token:rw

  generate-jwt:
    <<: *container-common
    environment:
      <<: *default-variables
      AUTH_OIDC_CA_KEY: ${AUTH_OIDC_CA_KEY-}
      AUTH_OIDC_CA_KEY_PASSWORD: ${AUTH_OIDC_CA_KEY_PASSWORD-}
    volumes:
      - ./build/bin/key-manager:/bin/main:ro
      - ./deps/config/ca:/ca:ro
    command: utils generate-jwt --sub=${SUB-tenant0|user0} --scope=${SCOPE-"*:*"} --expiration=${EXPIRATION-72h}

  import-secrets:
    <<: *container-common
    networks:
      - hashicorp
      - qkm
    environment:
      <<: *default-variables
      <<: *qkm-common
      IMPORT_STORE_NAME: ${IMPORT_STORE_NAME-}
    volumes:
      - ./deps/config/manifests:/manifests:ro
      - ./build/bin/key-manager:/bin/main:ro
      - hashicorp-token:/vault/token:rw
    command: import secrets

networks:
  quorum:
    external:
      name: quorum
  besu:
    external:
      name: besu
  hashicorp:
    external:
      name: hashicorp
  qkm:
    external:
      name: deps_qkm

volumes:
  hashicorp-token:
    external:
      name: hashicorp-token

