# The following environment variables are substituted if present
# * QUORUM_CONSENSUS: default to istanbul
# * QUORUM_DOCKER_IMAGE: default to quorumengineering/quorum:2.7.0
# * QUORUM_TX_MANAGER_DOCKER_IMAGE: default to quorumengineering/tessera:0.10.6
# * QUORUM_GETH_ARGS: extra geth arguments to be included when running geth
# To use Constellation, set QUORUM_TX_MANAGER_DOCKER_IMAGE to Constellation docker image,
# e.g.: QUORUM_TX_MANAGER_DOCKER_IMAGE=quorumengineering/constellation:0.3.2 docker-compose up -d
# To use Remix, set QUORUM_GETH_ARGS="--rpccorsdomain https://remix.ethereum.org"
version: "3.7"

x-quorum-def:
  &quorum-def
  restart: "on-failure"
  image: quorumengineering/quorum:20.10.0
  expose:
    - 30303
    - 8545
  labels:
    com.quorum.consensus: ${QUORUM_CONSENSUS:-istanbul}
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s
  entrypoint:
    - /bin/sh
    - -c
    - |

      if [ ! -z $${TESSERA_CLIENT} ]; then
        for i in $$(seq 1 100); do
          set -e
          if [ "I'm up!" == "$$(wget --timeout 10 -qO- --proxy off $${TESSERA_CLIENT}/upcheck)" ];
            then break
          else
            echo "Waiting for Tessera..."
            sleep 2
          fi
        done
      fi

      mkdir -p /data/dd;
      cp -r /quorum/* /data/dd/;
      geth --datadir=/data/dd init /config/genesis.json;
      cp /config/keys/accountkey /data/dd/keystore/key;
      cp /config/keys/nodekey /data/dd/geth/nodekey;
      geth \
      --datadir /data/dd \
      --nodiscover \
      --permissioned \
      --verbosity 3 \
      --istanbul.blockperiod 5 --mine --minerthreads 1 --emitcheckpoints \
      --syncmode full --nousb \
      --networkid $${QUORUM_NETWORK_ID:-10} \
      --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpccorsdomain "*" --rpcvhosts "*" --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,$${QUORUM_CONS_ALGO:-istanbul} \
      --ws --wsaddr 0.0.0.0 --wsport 8546 --wsorigins "*" --wsapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,$${QUORUM_CONS_ALGO:-istanbul} \
      --port 30303 \
      --identity node$${NODE_ID}-$${QUORUM_CONS_ALGO:-istanbul} \
      --unlock 0 \
      --allow-insecure-unlock \
      --password /config/passwords.txt
      ;

x-tessera-def:
  &tessera-def
  image: quorumengineering/tessera:21.1.0
  expose:
    - 9000
    - 9080
  restart: "no"
  healthcheck:
    test: ["CMD-SHELL", "[ -S /data/tm/tm.ipc ] || exit 1"]
    interval: 3s
    timeout: 3s
    retries: 20
    start_period: 5s
  entrypoint:
    - /bin/sh
    - -c
    - |
      mkdir -p /data/tm/;
      rm -rf /data/tm/*;
      cp /config/keys/tm.* /data/tm/ ;

          cat <<EOF > /data/tm/tessera-config-09.json
          {
            "useWhiteList": false,
            "jdbc": {
              "username": "sa",
              "password": "",
              "url": "jdbc:h2:./data/tm/db;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=0",
              "autoCreateTables": true
            },
            "serverConfigs":[
            {
              "app":"ThirdParty",
              "enabled": true,
              "serverAddress": "http://$$(hostname -i):9080",
              "communicationType" : "REST"
            },
            {
              "app":"Q2T",
              "enabled": true,
              "serverAddress": "unix:/data/tm/tm.ipc",
              "communicationType" : "REST"
            },
            {
              "app":"P2P",
              "enabled": true,
              "serverAddress": "http://$$(hostname -i):9000",
              "sslConfig": {
                "tls": "OFF"
              },
              "communicationType" : "REST"
            }
            ],
            "peer": [
               {
                   "url": "http://tessera1:9000"
               },
               {
                   "url": "http://tessera2:9000"
               },
               {
                   "url": "http://tessera3:9000"
               }
            ],
            "keys": {
              "passwords": [],
              "keyData": [
                {
                  "config": $$(cat /data/tm/tm.key),
                  "publicKey": "$$(cat /data/tm/tm.pub)"
                }
              ]
            },
            "alwaysSendTo": []
          }
      EOF
          cat /data/tm/tessera-config-09.json
          java -Xms128M -Xmx128M -jar /tessera/tessera-app.jar -configfile /data/tm/tessera-config-09.json

services:
  quorum1:
    <<: *quorum-def
    ports:
      - 21001:8545/tcp
      - 30303
    environment:
      - NODE_ID=1
      - PRIVATE_CONFIG=${PRIVATE_CONFIG:-/data/tm/tm.ipc}
      - TESSERA_CLIENT=172.16.238.21:9000
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/validator1:/config/keys
      - vol1:/data
    depends_on:
      - tessera1
    networks:
      quorum:
        ipv4_address: 172.16.238.11

  tessera1:
    <<: *tessera-def
    ports:
      - 9081:9080
    environment:
      - PRIVATE_CONFIG=${PRIVATE_CONFIG:-/data/tm/tm.ipc}
      - TESSERA_CONFIG_TYPE="-09"
    volumes:
      - ./config/quorum/networkFiles/tessera1:/config/keys
      - vol1:/data
    networks:
      quorum:
        ipv4_address: 172.16.238.21

  quorum2:
    <<: *quorum-def
    ports:
      - 21002:8545/tcp
      - 30303
    environment:
      - NODE_ID=2
      - PRIVATE_CONFIG=${PRIVATE_CONFIG:-/data/tm/tm.ipc}
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
      - TESSERA_CLIENT=172.16.238.22:9000
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/validator2:/config/keys
      - vol2:/data
    depends_on:
      - tessera2
    networks:
      quorum:
        ipv4_address: 172.16.238.12

  tessera2:
    <<: *tessera-def
    ports:
      - 9082:9080
    environment:
      - PRIVATE_CONFIG=${PRIVATE_CONFIG:-/data/tm/tm.ipc}
      - TESSERA_CONFIG_TYPE="-09"
    volumes:
      - ./config/quorum/networkFiles/tessera2:/config/keys
      - vol2:/data
    networks:
      quorum:
        ipv4_address: 172.16.238.22

  quorum3:
    <<: *quorum-def
    ports:
      - 21003:8545/tcp
      - 30303
    environment:
      - NODE_ID=3
      - PRIVATE_CONFIG=${PRIVATE_CONFIG:-/data/tm/tm.ipc}
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
      - TESSERA_CLIENT=172.16.238.23:9000 
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/validator3:/config/keys
      - vol3:/data
    depends_on:
      - tessera3
    networks:
      quorum:
        ipv4_address: 172.16.238.13

  tessera3:
    <<: *tessera-def
    ports:
      - 9083:9080
    environment:
      - PRIVATE_CONFIG=${PRIVATE_CONFIG:-/data/tm/tm.ipc}
      - TESSERA_CONFIG_TYPE="-09"
      - NODE_ID=8
    volumes:
      - ./config/quorum/networkFiles/tessera3:/config/keys
      - vol3:/data
    networks:
      quorum:
        ipv4_address: 172.16.238.23

  quorum4:
    <<: *quorum-def
    ports:
      - 21004:8545/tcp
      - 30303
    environment:
      - NODE_ID=4
      - PRIVATE_CONFIG=ignore
      - QUORUM_CONSENSUS=${QUORUM_CONS_ALGO:-istanbul}
    volumes:
      - ./config/quorum/passwords.txt:/config/passwords.txt
      - ./config/quorum/${QUORUM_CONS_ALGO:-istanbul}Genesis.json:/config/genesis.json
      - ./config/quorum/support:/quorum
      - ./config/quorum/networkFiles/validator4:/config/keys
    networks:
      quorum:
        ipv4_address: 172.16.238.14

networks:
  quorum:
    external:
      name: quorum

volumes:
  vol1:
  vol2:
  vol3:
