name: Update OpenAPI doc
on:
  push:
    branches:
      - master
      - 70-openapi
    tags:
      - 'v*'

env:
  GHPAGES_DIR: gh-pages
  GHPAGES_REF: refs/heads/gh-pages
jobs:
  update-version:
    name: Update API versions list and specs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Checkout github pages
        uses: actions/checkout@v2
        with:
          ref: ${{ env.GHPAGES_REF }}
          path: ${{ env.GHPAGES_DIR }}

      - name: Generate specs
        run: |
          make install-swagger
          export PATH=$(go env GOPATH)/bin:$PATH
          make gen-swagger

      - name: Combine swagger files
        run: |
          npm install swagger-combine@1.3.0
          export PATH="$PATH:$(pwd)/node_modules/.bin"
          swagger-combine .docops/swagger-combine.yml -o .docops/orchestrate.json

      - name: Install dependencies
        run: |
          cd ./.github/actions/update-api-doc
          npm ci

      - name: Update version list and copy spec files
        uses: ./.github/actions/update-api-doc
        with:
          specs-source: docs/swagger.json
          gh-pages-branch: ${{ env.GHPAGES_DIR }}

      - name: Log generated changes
        run: |
          echo "::group::gh-pages dist dir"
          ls -la ${{ env.GHPAGES_DIR }}
          echo "::endgroup::"
          echo "::group::versions.json"
          cat ${{ env.GHPAGES_DIR }}/versions.json
          echo "::endgroup::"
          echo "::group::yaml-spec"
          cat ${{ env.GHPAGES_DIR }}/keymanager.latest.json
          echo "::endgroup::"

      - name: Deploy changes to gh-pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ env.GHPAGES_DIR }} # The branch the action should deploy to.
          FOLDER: ${{ env.GHPAGES_DIR }} # The folder the action should deploy.
          CLEAN: false
          PRESERVE: true
